### ISSUE TITLE
fix potential serial locked in timeout issues

### ISSUE THREAD

**Issue by guihomework** [ubi-agni/TactileGlove#1]
while developing SerialProtocol the libio was re-used from this project and we found out (email 2019-01-17) the serial protocol node was somehow unable to reconnect in certain cases due to timeout locking the port.

one solution found was to add 
```
FD_ZERO(&fdset); 
FD_SET (fd, &fdset);
```
before this line 
https://github.com/ubi-agni/TactileGlove/blob/master/linux/libio/SerialInput.cpp#L125

but with no acces to hardware easily now, I am not being able to test if this changes affects things, so I write this as an issue here to remember to do it later.

**Comment by rhaschke** [comment]
Indeed, according to the [`pselect` doc](https://linux.die.net/man/3/fd_set), the file set needs to be reset before each call to `pselect`, because they are potentially modified by `pselect`:
> On exit, the sets are modified in place to indicate which file descriptors actually changed status.

**Comment by rhaschke** [comment]
Fixed via 305267a.
